Repository IdiotFrogs/MemorySeal-Android, pull requests merged in 2025-05, with the labels that each got.

#151 Custom Text 생성
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/component/MSButton.kt
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/component/MSText.kt
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/component/MSTextField.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/login/LoginScreen.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/login/component/LoginButton.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/signup/SignUpScreen.kt
  feature/home/src/main/java/com/idiotfrogs/home/component/HomeHeader.kt
  feature/home/src/main/java/com/idiotfrogs/home/component/HomeJoinContainer.kt
  feature/home/src/main/java/com/idiotfrogs/home/component/HomeMenuFab.kt
  feature/home/src/main/java/com/idiotfrogs/home/component/HomeTabBar.kt
  feature/home/src/main/java/com/idiotfrogs/home/component/HomeTicket.kt
Labels: :art: Design

#147 🔀 :: (#146) DropdownMenu 리팩토링
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/component/MSMenuFab.kt
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/model/MSMenuFabModel.kt
  feature/home/src/main/java/com/idiotfrogs/home/HomeScreen.kt
  feature/home/src/main/java/com/idiotfrogs/home/component/HomeMenuFab.kt
Labels: 🔨 Refactor

#153 🔀 :: (#152) 갤러리 및 키보드 로직 함수화
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/util/KeyboardUtil.kt
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/util/PickerUtil.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/signup/SignUpScreen.kt
Labels: 🔨 Refactor

#149 🔀 :: (#148) TextField border 조건 iOS와 통일
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/component/MSTextField.kt
Labels: ✨ Feature
