Repository IdiotFrogs/MemorySeal-Android, pull requests merged in 2025-03, with the labels that each got.

#121 🔀 :: (#120) 로그인 네비게이션 처리
  app/build.gradle.kts
  app/src/main/java/com/idiotfrogs/memoryseal/MainActivity.kt
  build-logic/src/main/kotlin/com/idiotfrogs/memoryseal/ComposeAndroid.kt
  build-logic/src/main/kotlin/convention.android.feature.gradle.kts
  core/data/src/main/java/com/idiotfrogs/data/LoginManager.kt
  core/navigation/build.gradle.kts
  core/navigation/src/main/java/com/idiotfrogs/navigation/Routes.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/LoginScreen.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/login/LoginScreen.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/login/LoginViewModel.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/util/LocalLoginManager.kt
  gradle/libs.versions.toml
Labels: ✨ Feature

#128 Dependabot 제거
  .github/dependabot.yml
Labels: ⚡ Simple

#130 targetSdk 35 및 DI 모듈 생성
  baselineProfile/build.gradle.kts
  build-logic/src/main/kotlin/com/idiotfrogs/memoryseal/KotlinAndroid.kt
  core/di/.gitignore
  core/di/build.gradle.kts
  core/di/consumer-rules.pro
  core/di/proguard-rules.pro
  core/di/src/main/AndroidManifest.xml
  settings.gradle.kts
Labels: 🔨 Refactor

#134 🔀 :: (#131) 스플래시 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/idiotfrogs/memoryseal/MainActivity.kt
  app/src/main/res/values/themes.xml
  common/resource/src/main/res/drawable/img_splash.png
  gradle/libs.versions.toml
Labels: ✨ Feature

#135 🔀 :: (#133) 로그인 화면 구성
  app/src/main/java/com/idiotfrogs/memoryseal/MainActivity.kt
  common/resource/build.gradle.kts
  common/resource/src/main/java/com/idiotfrogs/resource/Font.kt
  common/resource/src/main/res/drawable/ic_apple_logo.xml
  common/resource/src/main/res/drawable/ic_google_logo.xml
  common/resource/src/main/res/drawable/ic_login_logo.png
  common/resource/src/main/res/font/hs_santokki.ttf
  common/resource/src/main/res/font/pretendard_bold.ttf
  common/resource/src/main/res/font/pretendard_medium.ttf
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/util/DevicePreview.kt
  core/designsystem/src/main/java/com/idiotfrogs/designsystem/util/DpToSp.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/idiotfrogs/auth/login/LoginScreen.kt
  feature/auth/src/main/java/com/idiotfrogs/auth/login/component/LoginButton.kt
Labels: ✨ Feature
